<template>
  <view class="content">
    <image mode="aspectFit" src="../../static/images/university_logo.png" class="logo"></image>
    <view class="userAgreementBox">
      <view>
        This is an AI-enhanced vocabulary learning tool that aims to enhance XJTLU students' EAP vocabulary learning
        experience. This tool is developed by a group of XJTLU lecturers (Minyue Zhou, Anastacia Naidoo, Xiaoqing Bi,
        Fei Cheng) as part of their TDF project.
      </view>
      <view>
        You are being invited to participate in the pilot study of this platform. Before you decide whether to
        participate, it is important for you to understand what it will involve:
      </view>
      <view>
        • Your XJTLU email will be collected in the process of identification and will be checkable by the researchers
        and programmers. This is simply to ensure that we can match you to your teacher in the system, so that your
        teacher can use game functions on this program with you in class.
      </view>
      <view>
        • The data generated by you, for example, the vocabulary bank you create, will be recorded on our own backend
        server for the platform’s normal operation, debugging and research purposes. We will encrypt the data
        transmission process to avoid being hacked during the HTTP call. Therefore, there will be very minimal risk of
        personal information leakage.
      </view>
      <view>
        • The information you provide will not allow you to be identified in any research outputs/publications.
      </view>
      <view>
        • All other reasonable, foreseeable measures and efforts to ensure that the data is kept confidential will be
        taken.
      </view>
      <view>
        Feel free to contact the principle investigator, Minyue Zhou, via email at minyue.zhou@xjtlu.edu.cn should you
        need more information, or have any questions or concerns.
      </view>
      <view>
        We would like to stress that you do not have to accept this invitation and should only agree to take part if you
        want to. Also, you can ask for access to the information you provide at any time and request the destruction of
        that information if you wish.
      </view>
    </view>
  </view>
</template>
<script lang="ts">
import {defineComponent} from 'vue'

export default defineComponent({})
</script>
<style scoped lang="less">
@import './index.less';
</style>