name: Build and Push Docker Image
on:
  push:
    branches:
      - dev/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn run build:h5
      - name: Zip
        run: zip -r ./dist.zip ./dist
      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: latest
          path: ./dist.zip
          repo-token: ${{ secrets.REPO_TOKEN }}